### ISSUE TITLE
4.x version doesn't work with PubNub

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/RingCentral.Net#22]
```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> RingCentral.RestClient.Post(System.String, System.Object, System.Object)'.
   at RingCentral.Subscription.Subscribe()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RingCentral.Subscription.Subscribe()
   at RingCentralPubNubDemo.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in /Users/tyler.liu/src/dotnet/RingCentralPubNubDemo/RingCentralPubNubDemo/Program.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at RingCentralPubNubDemo.Program.Main(String[] args) in /Users/tyler.liu/src/dotnet/RingCentralPubNubDemo/RingCentralPubNubDemo/Program.cs:line 18
```

**Comment by tylerlong** [comment]
- RingCentral.Net 4.x is compatible with RingCentral.Net.Pubnub/RingCentral.Net.PubnubPCL 1.4 or later versions.
- RingCentral.Net 3.x is compatible with RingCentral.Net.Pubnub/RingCentral.Net.PubnubPCL 1.3.1 or earlier versions.
