### ISSUE TITLE
Task`1[RingCentral.RestClient]' is not assignable to service 'RingCentral.RestClient'.

### ISSUE THREAD

**Issue by fp-jcorriveau** [ringcentral/RingCentral.Net#76]
When trying to register a RestClient, I get this exception

System.ArgumentException: The type 'System.Threading.Tasks.Task`1[RingCentral.RestClient]' is not assignable to service 'RingCentral.RestClient'.
   at Autofac.Builder.RegistrationBuilder.CreateRegistration(Guid id, RegistrationData data, IInstanceActivator activator, IResolvePipelineBuilder pipelineBuilder, Service[] services, IComponentRegistration target)
   at Autofac.Builder.RegistrationBuilder.CreateRegistration[TLimit,TActivatorData,TSingleRegistrationStyle](IRegistrationBuilder`3 builder)
   at Autofac.Builder.RegistrationBuilder.RegisterSingleComponent[TLimit,TActivatorData,TSingleRegistrationStyle](IComponentRegistryBuilder cr, IRegistrationBuilder`3 builder)
   at Autofac.RegistrationExtensions.<>c__DisplayClass42_0`1.<Register>b__0(IComponentRegistryBuilder cr)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.UpdateRegistry(IComponentRegistryBuilder componentRegistry)
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.Core.Registration.ModuleRegistrar.<.ctor>b__1_0(IComponentRegistryBuilder reg)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()

```csharp
        // using autofac
        builder.Register(async c =>
        {
            var restClient = new RestClient(Settings.ClientId, Settings.ClientSecret, Settings.Server);
            await restClient.Authorize(Settings.JwtToken); // if I remove the authorize, it seams to be ok
            return restClient;
        }).As<RestClient>().SingleInstance();
```

**Comment by fp-jcorriveau** [comment]
Yes indeed... my bad, I took it for granted, but since it's async, it returns a Tas
